id: f87908e0f433488b9d9f46c962acbf90
initial_creation_type: ocr
source_metadata:
  volumes:
    80ce7a06f8be4d3cae675bb69bb6088c:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
